  user:
    maximum_name: 50
    maximum_email: 255
    minimum_pass: 6
    size: 50
    number: 2
  users_helper:
    size: 80
  sessions_controller:
    bit: "1"
  email:
    from: "noreply@example.com"

